# Generated by Django 5.0.6 on 2024-07-06 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('clienteid', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('productoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('servicioid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=50)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuarioid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('passwordhash', models.CharField(max_length=50)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('tipousuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('ordenid', models.AutoField(primary_key=True, serialize=False)),
                ('fechaorden', models.DateTimeField(auto_now_add=True)),
                ('total', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('clienteid', models.ForeignKey(db_column='clienteid', on_delete=django.db.models.deletion.CASCADE, to='easyTruck.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Detalleorde',
            fields=[
                ('detalleid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=50)),
                ('preciounitario', models.CharField(max_length=50)),
                ('ordenid', models.ForeignKey(db_column='ordenid', on_delete=django.db.models.deletion.CASCADE, to='easyTruck.ordenes')),
                ('productoid', models.ForeignKey(db_column='productoid', on_delete=django.db.models.deletion.CASCADE, to='easyTruck.productos')),
                ('servicioid', models.ForeignKey(db_column='servicioid', on_delete=django.db.models.deletion.CASCADE, to='easyTruck.servicios')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='usuarioid',
            field=models.ForeignKey(db_column='usuarioid', on_delete=django.db.models.deletion.CASCADE, to='easyTruck.usuarios'),
        ),
    ]
