# Generated by Django 5.0.6 on 2024-07-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyTruck', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
        migrations.RenameModel(
            old_name='Ordenes',
            new_name='Ordene',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteid', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('usuarioid', models.ForeignKey(db_column='usuarioid', on_delete=django.db.models.deletion.CASCADE, to='easyTruck.usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='ordene',
            name='clienteid',
            field=models.ForeignKey(db_column='clienteid', on_delete=django.db.models.deletion.CASCADE, to='easyTruck.cliente'),
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
